name: Python 3.9

on:
  # Trigger the workflow on push, but only for the main branch
  push:
    branches:
      - main

jobs:
  format_lint_and_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    steps:

      - name: Clone repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pip install -r <(pipenv lock -d -r)

      - name: Format with black
        run: |
          black .

      - name: Lint with flake8
        run: |
          flake8 --ignore=E203,W503 --max-line-length=100 .

      - name: Test with pytest
        run: |
          pytest tests

      - name: Commit formatted sources and push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github@example.com"
          if git commit -am "GitHub Actions: format with black"; then
            git push
          fi
